[versions]
agp = "8.8.2"
androidTools = "31.9.1"
cameraxVersion = "1.4.2"
kotlin = "2.0.21"
junit = "4.13.2"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.4"
androidx-material = "1.12.0"
coroutine = "1.9.0"
androidxComposeBom = "2025.03.01"
androidxComposeCompiler = "1.5.15"
ksp = "2.0.21-1.0.25"
koin = "4.0.0"
mockk = "1.13.9"
lottie = "6.6.4"
compose-livedata = "1.7.8"
android-arch-core = "2.2.0"
lifecycle-runtime = "2.8.7"
navigation = "2.7.0-alpha07"
material3Android = "1.3.1"
junitVersion = "4.13.2"
androidxJunit = "1.2.1"
jetbrainsKotlinJvm = "2.0.21"
room = "2.7.0-rc03"

[libraries]
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-livedata" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
core-common = { module = "androidx.arch.core:core-common", version.ref = "android-arch-core" }
core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "android-arch-core" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "android-arch-core" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Android" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraxVersion" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraxVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraxVersion" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
junit = { group = "androidx.test.junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
# End


[bundles]
android = ["androidx-appcompat", "androidx-material", "androidx-constraintlayout", "androidx-activity-compose"]
core = ["androidx-core-ktx", "core-common", "core-runtime", "core-testing", "lifecycle-runtime"]
coroutines = ["coroutine-core", "coroutine-android", "coroutine-test"]
room = ["androidx-room-ktx", "room-gradlePlugin"]
lottie = ["lottie", "lottie-compose"]
compose = ["androidx-activity-compose", "compose-ui", "compose-graphics", "compose-tooling", "compose-runtime-livedata", "androidx-material3"]
androidtest = ["androidx-espresso-core", "junit-test"]
test = ["junit", "mockk", "coroutine-test", "koin-test", "kotlin-test", "kotlin-test-junit"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Plugins defined by this project
flashback-android-application = { id = "flashback.android.application", version = "unspecified" }
flashback-android-application-compose = { id = "flashback.android.application.compose", version = "unspecified" }
flashback-android-library = { id = "flashback.android.library", version = "unspecified" }
flashback-android-library-compose = { id = "flashback.android.library.compose", version = "unspecified" }
flashback-android-room = { id = "flashback.android.room", version = "unspecified" }
# End